# application.properties
spring:
  datasource:
    url: jdbc:mysql://192.168.0.153:3306/test
    username: root
    password:
mybatis:
  type-aliases-package: com.example.springboot.dto
  type-handlers-package: com.example.springboot.mapper
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30